--Exibi a relação de RTR emitidos


SELECT
	--servicoatendimento.idservicoatendimento,
	ATENDIMENTO.IDUSUARIO,
	USUARIO.NOME NOMEVENDEDOR,
	ATENDIMENTO.IDPARCEIRO,
	PARCEIRO.NOME NOMEPARCEIRO,
	ATENDIMENTO.DATAINICIO,
	--to_char(atendimento.datainicio, 'DD/MM/YYYY') data_inicio,
	COALESCE(SERVICOATENDIMENTO.OBSERVACAO, 'N POSSUI') OBSERVACAOEVIDENCIA,
	--servicoatendimento.idservico,
	SERVICO.DESCRICAO DESCRICAOSERVIÇO,
	--COALESCE(atendimento.idtipodeatendimento, 0) idtipodeatendimento,
	COALESCE(TIPODEATENDIMENTO.DESCRICAO, 'N POSSUI') DESCRICAOATENDIMENTO,
	--servicoatendimento.idatendimento,
	--COALESCE(servicoatendimento.idsafra, 0) idsafra,
	COALESCE(SAFRA.DESCRICAO, 'N POSSUI') DESCRICAOSAFRA,
	--COALESCE(servicoatendimento.idpropriedade, 0) idpropriedade,
	COALESCE(PROPRIEDADE.DESCRICAO, 'N POSSUI') DESCRIAOPROPRIEDADE,
	--servicoatendimento.idlocal,
	LOCAL.DESCRICAO DESCRICAOLOCAL,
	CASE
		WHEN SERVICOATENDIMENTO.RASCUNHO = 1 THEN 'Rascunho'
		ELSE 'Concluido'
	END STATUSATENDIMENTO
	--servicoatendimento.rascunho
	--to_date(to_char(servicoatendimento.created_at, 'DD/MM/YYYY'),'DD/MM/YYYY') criado_em -- Corrigir esse negócio aqui, por favor
FROM
	SERVICOATENDIMENTO
	JOIN SERVICO ON (SERVICO.IDSERVICO = SERVICOATENDIMENTO.IDSERVICO)
	JOIN ATENDIMENTO ON (
		ATENDIMENTO.IDATENDIMENTO = SERVICOATENDIMENTO.IDATENDIMENTO
	)
	JOIN USUARIO ON (USUARIO.IDUSUARIO = ATENDIMENTO.IDUSUARIO)
	JOIN PARCEIRO ON (PARCEIRO.IDPARCEIRO = ATENDIMENTO.IDPARCEIRO)
	LEFT JOIN PROPRIEDADE ON PROPRIEDADE.IDPROPRIEDADE = SERVICOATENDIMENTO.IDPROPRIEDADE
	LEFT JOIN TIPODEATENDIMENTO ON TIPODEATENDIMENTO.IDTIPODEATENDIMENTO = ATENDIMENTO.IDTIPODEATENDIMENTO
	LEFT JOIN SAFRA ON SAFRA.IDSAFRA = SERVICOATENDIMENTO.IDSAFRA
	LEFT JOIN LOCAL ON LOCAL.IDLOCAL = SERVICOATENDIMENTO.IDLOCAL
WHERE
	SERVICO.DESCRICAO LIKE 'LAUDO%'