--Este script tem como função listar as sincronização dos vendedores no aplicativo mobile do Clover CRM 

SELECT
	DATAHORAINICIO::DATE AS DATA,
	DATE_TRUNC('second', DATAHORAINICIO::TIME) HORAINICIO,
	DATE_TRUNC('second', DATAHORAFIM::TIME) HORAFIM,
	DATE_TRUNC('second', DATAHORAFIM - DATAHORAINICIO) AS TEMPO_SINC,
	USUARIO.LOGIN,
	USUARIO.IDUSUARIO,
	DCLOGSTATE.DBID,
	DCLOGSTATE.POCKETVERSION,
	CASE TIPOSINCRONIZACAO
		WHEN 0 THEN 'Sinc Normal'
		WHEN 1 THEN 'Envio Dados'
		WHEN 3 THEN 'Geração Base'
	END AS TIPOSINC
FROM
	DCLOGSTATE
	INNER JOIN DCDBID ON DCDBID.DBID = DCLOGSTATE.DBID
	INNER JOIN USUARIO ON USUARIO.IDUSUARIO = DCDBID.IDUSUARIO
WHERE
	DATAHORAINICIO > CURRENT_DATE
	ORDER BY HORAINICIO DESC