WITH
	TB_PARCEIROCLOVER AS (
		SELECT
			PROPRIEDADE.IDGRUPOEMPRESARIAL,
			PARCEIRO.IDPARCEIRO,
			PARCEIRO.NOME NOMEPARCEIRO,
			PROPRIEDADE.CODIGO,
			PROPRIEDADE.IDPROPRIEDADE,
			PROPRIEDADE.AREATOTAL,
			PROPRIEDADE.DESCRICAO DESCRICAOPROPRIEDADE,
			LOCAL.DESCRICAO LOCALDESCRICAO,
			PROPRIEDADE.CODIGO,
			PROPRIEDADE.IDCIDADE,
			PROPRIEDADE.IDUSUARIO,
			USUARIO.NOME NOMEVENDEDOR,
			PROPRIEDADE.LONGITUDE,
			PROPRIEDADE.LATITUDE,
			PROPRIEDADE.BLOQUEADO,
			LOCAL.ATIVO,
			LOCAL.IDLOCAL,
			POSSE.DATAVENDA,
			CASE
				WHEN POSSE.DATAVENDA < CURRENT_DATE THEN 'INATIVO'
				ELSE 'ATIVA'
			END AS POSSE_DATAVENDA_STATUS,
			ARRENDAMENTO.DATATERMINO -- usuario.nome n
		FROM
			PROPRIEDADE -- Lista todas as propriedade
			JOIN USUARIO ON PROPRIEDADE.IDUSUARIO = USUARIO.IDUSUARIO
			JOIN VINCULOIMOBILIARIO ON VINCULOIMOBILIARIO.IDPROPRIEDADE = PROPRIEDADE.IDPROPRIEDADE
			JOIN LOCAL ON VINCULOIMOBILIARIO.IDLOCAL = LOCAL.IDLOCAL
			JOIN PARCEIRO ON LOCAL.IDPARCEIRO = PARCEIRO.IDPARCEIRO
			LEFT JOIN POSSE ON POSSE.IDPOSSE = VINCULOIMOBILIARIO.IDVINCULOIMOBILIARIO
			LEFT JOIN ARRENDAMENTO ON ARRENDAMENTO.IDARRENDAMENTO = VINCULOIMOBILIARIO.IDVINCULOIMOBILIARIO
		WHERE
			PARCEIRO.ATIVO <> 0
			AND PARCEIRO.IDPARCEIRO = 50
			AND (
				CASE
					WHEN POSSE.DATAVENDA < CURRENT_DATE THEN 0
					ELSE 1
				END
			) = 1
	)