-- Exibi a relaçao de proproiedade e parceiros
WITH
	TB_REGIAOVENDEDOR AS (
		SELECT
			REGIAOLOCAL.IDLOCAL REGIAOLOCAL_IDLOCAL,
			REGIAOLOCAL.IDREGIAOLOCAL REGIAOLOCAL_IDREGIAOLOCAL,
			REGIAOLOCAL.IDREGIAO REGIAOLOCAL_IDREGIAO,
			REGIAOLOCAL.DATAINICIOVIGENCIA REGIAOLOCAL_DATAINICIOVIGENCIA,
			REGIAOLOCAL.DATAFIMVIGENCIA REGIAOLOCAL_DATAFIMVIGENCIA,
			LOCAL.IDLOCAL LOCAL_IDLOCAL,
			REGIAO.NOME REGIAO_NOME,
			REGIAO.IDUSUARIO REGIAO_IDUSUARIO,
			USUARIO.NOME USUARIO_NOME,
			USUARIO.ATIVO USUARIO_ATIVO,
			CASE
				WHEN USUARIO.ATIVO = 1 THEN 'ATIVO'
				ELSE 'INATIVO'
			END STATUS_VENDEDOR,
			PARCEIRO.NOME NOMEPARCEIRO,
			LOCAL.DESCRICAO LOCAL_DESCRICAO,
			LOCAL.ENDERECO LOCAL_ENDERECO,
			LOCAL.ATIVO LOCAL_ATIVO,
			CASE
				WHEN LOCAL.ATIVO = 1 THEN 'ATIVO'
				ELSE 'INATIVO'
			END STATUS_LOCAL,
			LOCAL.CHAVEERP LOCAL_CHAVEERP,
			PROPRIEDADE.IDCIDADE PROPRIEDADE_IDCIDADE,
			CIDADE.DESCRICAO CIDADE_DESCRICAO,
			PROPRIEDADE.IDPROPRIEDADE PROPRIEDADE_IDPROPRIEDADE,
			PROPRIEDADE.DESCRICAO PROPRIEDADE_DESCRICAO,
			PROPRIEDADE.LONGITUDE PROPRIEDADE_LONGITUDE,
			PROPRIEDADE.LATITUDE PROPRIEDADE_LATITUDE,
			POSSE.DATAVENDA,
			CASE
				WHEN POSSE.DATAVENDA < CURRENT_DATE THEN 'INATIVO'
				ELSE 'ATIVA'
			END AS POSSE_DATAVENDA_STATUS,
			ARRENDAMENTO.DATATERMINO,
			ROW_NUMBER() OVER (
				PARTITION BY
					PROPRIEDADE.DESCRICAO
				ORDER BY
					PROPRIEDADE.IDPROPRIEDADE
			) INDICE_REGISTRO_LOCAL
		FROM
			REGIAOLOCAL
			JOIN LOCAL ON LOCAL.IDLOCAL = REGIAOLOCAL.IDLOCAL
			JOIN REGIAO ON REGIAO.IDREGIAO = REGIAOLOCAL.IDREGIAO
			JOIN USUARIO ON USUARIO.IDUSUARIO = REGIAO.IDUSUARIO
			JOIN VINCULOIMOBILIARIO ON VINCULOIMOBILIARIO.IDLOCAL = REGIAOLOCAL.IDLOCAL
			JOIN PROPRIEDADE ON PROPRIEDADE.IDPROPRIEDADE = VINCULOIMOBILIARIO.IDPROPRIEDADE
			JOIN PARCEIRO ON LOCAL.IDPARCEIRO = PARCEIRO.IDPARCEIRO
			JOIN CIDADE ON CIDADE.IDCIDADE = PROPRIEDADE.IDCIDADE
			LEFT JOIN POSSE ON POSSE.IDPOSSE = VINCULOIMOBILIARIO.IDVINCULOIMOBILIARIO
			LEFT JOIN ARRENDAMENTO ON ARRENDAMENTO.IDARRENDAMENTO = VINCULOIMOBILIARIO.IDVINCULOIMOBILIARIO
		WHERE
			USUARIO.ATIVO = 1 -- -- Classifica os usuário ativos (0: Inativo || 1: Ativo)
			AND LOCAL.ATIVO = 1 -- Classifica os locais ativos (0: Inativo || 1: Ativo)
			AND (
				CASE
					WHEN POSSE.DATAVENDA < CURRENT_DATE THEN 0
					ELSE 1
				END
			) = 1
	)
SELECT
	TB_REGIAOVENDEDOR.REGIAOLOCAL_IDREGIAO,
	TB_REGIAOVENDEDOR.USUARIO_NOME,
	TB_REGIAOVENDEDOR.NOMEPARCEIRO,
	TB_REGIAOVENDEDOR.LOCAL_DESCRICAO,
	TB_REGIAOVENDEDOR.LOCAL_ENDERECO,
	TB_REGIAOVENDEDOR.PROPRIEDADE_IDCIDADE,
	TB_REGIAOVENDEDOR.CIDADE_DESCRICAO,
	TB_REGIAOVENDEDOR.PROPRIEDADE_IDPROPRIEDADE,
	TB_REGIAOVENDEDOR.PROPRIEDADE_DESCRICAO,
	TB_REGIAOVENDEDOR.PROPRIEDADE_LONGITUDE,
	TB_REGIAOVENDEDOR.PROPRIEDADE_LATITUDE,
	TB_REGIAOVENDEDOR.INDICE_REGISTRO_LOCAL
FROM
	TB_REGIAOVENDEDOR
WHERE
	TB_REGIAOVENDEDOR.INDICE_REGISTRO_LOCAL = 1
ORDER BY
	TB_REGIAOVENDEDOR.REGIAO_IDUSUARIO,
	PROPRIEDADE_DESCRICAO